version: '3.8'
services:
  tgi_ssh:
    image: tgi_ssh:2.4.0
    container_name: tgi_ssh
    ports:
      - "8080:3000"
      - "8081:22"
    environment:
      - PASSWORD=PASSWORD
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
                - "1"
              capabilities: [gpu]
    security_opt:
      - seccomp:unconfined
    tty: true
    stdin_open: true
    restart: unless-stopped
