version: '3.8'
services:
  tgi_ssh:
    image: tgi_ssh:3.3.2
    container_name: tgi_ssh
    ports:
      - "8080:80"
      - "8081:22"
    environment:
      - PASSWORD=PASSWORD
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - seccomp:unconfined
    tty: true
    stdin_open: true
    restart: unless-stopped
